### ISSUE TITLE
Quality of Life Changes & Some must have features in Hysp

### ISSUE THREAD

**Issue by Azathothas** [pwnwriter/hysp#14]
1. ####  Add/Use **`metadata`** in `config.toml`
> - Note : This should be an optional feature, toggled only if `config.toml` contains `[source].metadata`, else print `[source].metadata` not defined in config file (for self-hosting people)
> - Default config.toml should contain this field as all the backend work is already done

```toml
  [source]
  aarch = "Architecture"
  metadata = "https://raw.githubusercontent.com/metis-os/hysp-pkgs/main/data/metadata.toml" 
  remote = "https://raw.githubusercontent.com/metis-os/hysp-pkgs/main/data/"
  
  [local]
  home="/home/user/.local/share/hysp"
  bin="/home/user/.local/share/hysp/bin/" 
  data="/home/user/.local/share/hysp/data/"
```
- ##### Why ?
> 1. Implement cli to **`list all available packages`** based on [`metadata.toml`](https://github.com/metis-os/hysp-pkgs/blob/main/data/metadata.toml)
> ```bash
> hysp list (-a | --all) --> List all available Packages
> # Default: hysp cli to list only installed packages can be changed to something like: 
> hysp list (-i | --installed) --> List only Installed Packages
> ```
> ---
> 2. Implement cli to **`fuzzy search packages`** based on [`metadata.toml`](https://github.com/metis-os/hysp-pkgs/blob/main/data/metadata.toml)
> ```bash
> hysp search -p foo --> Should search for *foo*
> # Default: hysp cli to install packages should stick to using exact matches
> hysp install -p foo --> Should install exactly foo, based on foo.toml
> ```
> ---

2. ####  **`Allow Installing/Uninstalling multiple packages at once`** 
> ```bash
> hysp install -p foo bar xyz --> Should install all three, one after another based on their `.toml` files.
> # If it's not too much work, the search cli should also be able to search for multiple packages at once:
> hysp search -p foo bar xyz --> Should search & print info for all three, and if fuzzy search is already implemented, then it should cotinue to fuzzy search for all three
>
> #Similarly, the remove cmd should also be able to uninstall multiple packages at once
> hysp remove -p foo bar xyz --> Should uninstall all three, one after another based on $BIN/$PKG
> ```
